#!/usr/bin/env bash

set -euo pipefail

AGENT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
SRC_ROOT="$AGENT_ROOT/src"
CONFIG_ENV="$SRC_ROOT/config/runtime.env"
CONFIG_ENV_LOCAL="$SRC_ROOT/config/runtime.env.local"

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:${PATH:-}"
export PYTHONPATH="$SRC_ROOT:$AGENT_ROOT:${PYTHONPATH:-}"

mkdir -p "$AGENT_ROOT/runtime/logs" "$AGENT_ROOT/runtime/state" "$AGENT_ROOT/runtime/reports"

OVERRIDE_TRADING_MODE="${TRADING_MODE-}"
OVERRIDE_CODEX_MODEL="${CODEX_MODEL-}"
OVERRIDE_CODEX_BIN="${CODEX_BIN-}"
OVERRIDE_RISK_TIER="${RISK_TIER-}"
OVERRIDE_MAX_SINGLE_ORDER_NOTIONAL="${MAX_SINGLE_ORDER_NOTIONAL-}"
OVERRIDE_MAX_DAILY_NOTIONAL="${MAX_DAILY_NOTIONAL-}"
OVERRIDE_CODEX_EXEC_TIMEOUT_SEC="${CODEX_EXEC_TIMEOUT_SEC-}"
OVERRIDE_ENABLE_DSA_SIGNAL_LAYER="${ENABLE_DSA_SIGNAL_LAYER-}"
OVERRIDE_ENABLE_KRONOS_SIGNAL_LAYER="${ENABLE_KRONOS_SIGNAL_LAYER-}"
OVERRIDE_ENABLE_MARKET_FEED_LAYER="${ENABLE_MARKET_FEED_LAYER-}"
OVERRIDE_ENABLE_TECHNICAL_SIGNAL_LAYER="${ENABLE_TECHNICAL_SIGNAL_LAYER-}"
OVERRIDE_MARKET_FEED_PYTHON_BIN="${MARKET_FEED_PYTHON_BIN-}"
OVERRIDE_MARKET_FEED_TIMEFRAMES="${MARKET_FEED_TIMEFRAMES-}"
OVERRIDE_MARKET_FEED_NEWS_LIMIT="${MARKET_FEED_NEWS_LIMIT-}"
OVERRIDE_MARKET_FEED_DIR="${MARKET_FEED_DIR-}"
OVERRIDE_DSA_SIGNALS_PATH="${DSA_SIGNALS_PATH-}"
OVERRIDE_KRONOS_SIGNALS_PATH="${KRONOS_SIGNALS_PATH-}"
OVERRIDE_TECHNICAL_SIGNALS_PATH="${TECHNICAL_SIGNALS_PATH-}"
OVERRIDE_DAILY_PLAN_PATH="${DAILY_PLAN_PATH-}"
OVERRIDE_DAILY_PLAN_MARKDOWN_PATH="${DAILY_PLAN_MARKDOWN_PATH-}"
OVERRIDE_DYNAMIC_ALLOWLIST_PATH="${DYNAMIC_ALLOWLIST_PATH-}"
OVERRIDE_TODAY_ALLOWLIST_PATH="${TODAY_ALLOWLIST_PATH-}"
OVERRIDE_DAILY_USAGE_PATH="${DAILY_USAGE_PATH-}"
OVERRIDE_ACCOUNT_SNAPSHOT_PATH="${ACCOUNT_SNAPSHOT_PATH-}"
OVERRIDE_MARKET_CALENDAR_PATH="${MARKET_CALENDAR_PATH-}"
OVERRIDE_QUOTE_SNAPSHOT_CORE_PATH="${QUOTE_SNAPSHOT_CORE_PATH-}"
OVERRIDE_CANDIDATE_SNAPSHOT_PATH="${CANDIDATE_SNAPSHOT_PATH-}"
OVERRIDE_QUOTE_SNAPSHOT_CANDIDATES_PATH="${QUOTE_SNAPSHOT_CANDIDATES_PATH-}"
OVERRIDE_TRADABILITY_SNAPSHOT_PATH="${TRADABILITY_SNAPSHOT_PATH-}"
OVERRIDE_CATALYST_SNAPSHOT_PATH="${CATALYST_SNAPSHOT_PATH-}"
OVERRIDE_DECISIONS_LOG_PATH="${DECISIONS_LOG_PATH-}"
OVERRIDE_ORDERS_LOG_PATH="${ORDERS_LOG_PATH-}"
OVERRIDE_POSTMARKET_SUMMARY_PATH="${POSTMARKET_SUMMARY_PATH-}"
OVERRIDE_PAPER_STARTING_CASH="${PAPER_STARTING_CASH-}"
OVERRIDE_KRONOS_PYTHON_BIN="${KRONOS_PYTHON_BIN-}"
OVERRIDE_KRONOS_PROJECT_ROOT="${KRONOS_PROJECT_ROOT-}"
OVERRIDE_KRONOS_MODEL_NAME="${KRONOS_MODEL_NAME-}"
OVERRIDE_KRONOS_TOKENIZER_NAME="${KRONOS_TOKENIZER_NAME-}"
OVERRIDE_KRONOS_TIMEFRAME="${KRONOS_TIMEFRAME-}"
OVERRIDE_KRONOS_LOOKBACK_BARS="${KRONOS_LOOKBACK_BARS-}"
OVERRIDE_KRONOS_HORIZON_BARS="${KRONOS_HORIZON_BARS-}"
OVERRIDE_KRONOS_TEMPERATURE="${KRONOS_TEMPERATURE-}"
OVERRIDE_KRONOS_TOP_P="${KRONOS_TOP_P-}"
OVERRIDE_KRONOS_SAMPLE_COUNT="${KRONOS_SAMPLE_COUNT-}"
OVERRIDE_KRONOS_MIN_CONFIDENCE="${KRONOS_MIN_CONFIDENCE-}"

if [[ -f "$CONFIG_ENV" ]]; then
  set -a
  # shellcheck source=/dev/null
  source "$CONFIG_ENV"
  set +a
fi

if [[ -f "$CONFIG_ENV_LOCAL" ]]; then
  set -a
  # shellcheck source=/dev/null
  source "$CONFIG_ENV_LOCAL"
  set +a
fi

[[ -n "$OVERRIDE_TRADING_MODE" ]] && TRADING_MODE="$OVERRIDE_TRADING_MODE"
[[ -n "$OVERRIDE_CODEX_MODEL" ]] && CODEX_MODEL="$OVERRIDE_CODEX_MODEL"
[[ -n "$OVERRIDE_CODEX_BIN" ]] && CODEX_BIN="$OVERRIDE_CODEX_BIN"
[[ -n "$OVERRIDE_RISK_TIER" ]] && RISK_TIER="$OVERRIDE_RISK_TIER"
[[ -n "$OVERRIDE_MAX_SINGLE_ORDER_NOTIONAL" ]] && MAX_SINGLE_ORDER_NOTIONAL="$OVERRIDE_MAX_SINGLE_ORDER_NOTIONAL"
[[ -n "$OVERRIDE_MAX_DAILY_NOTIONAL" ]] && MAX_DAILY_NOTIONAL="$OVERRIDE_MAX_DAILY_NOTIONAL"
[[ -n "$OVERRIDE_CODEX_EXEC_TIMEOUT_SEC" ]] && CODEX_EXEC_TIMEOUT_SEC="$OVERRIDE_CODEX_EXEC_TIMEOUT_SEC"
[[ -n "$OVERRIDE_ENABLE_DSA_SIGNAL_LAYER" ]] && ENABLE_DSA_SIGNAL_LAYER="$OVERRIDE_ENABLE_DSA_SIGNAL_LAYER"
[[ -n "$OVERRIDE_ENABLE_KRONOS_SIGNAL_LAYER" ]] && ENABLE_KRONOS_SIGNAL_LAYER="$OVERRIDE_ENABLE_KRONOS_SIGNAL_LAYER"
[[ -n "$OVERRIDE_ENABLE_MARKET_FEED_LAYER" ]] && ENABLE_MARKET_FEED_LAYER="$OVERRIDE_ENABLE_MARKET_FEED_LAYER"
[[ -n "$OVERRIDE_ENABLE_TECHNICAL_SIGNAL_LAYER" ]] && ENABLE_TECHNICAL_SIGNAL_LAYER="$OVERRIDE_ENABLE_TECHNICAL_SIGNAL_LAYER"
[[ -n "$OVERRIDE_MARKET_FEED_PYTHON_BIN" ]] && MARKET_FEED_PYTHON_BIN="$OVERRIDE_MARKET_FEED_PYTHON_BIN"
[[ -n "$OVERRIDE_MARKET_FEED_TIMEFRAMES" ]] && MARKET_FEED_TIMEFRAMES="$OVERRIDE_MARKET_FEED_TIMEFRAMES"
[[ -n "$OVERRIDE_MARKET_FEED_NEWS_LIMIT" ]] && MARKET_FEED_NEWS_LIMIT="$OVERRIDE_MARKET_FEED_NEWS_LIMIT"
[[ -n "$OVERRIDE_MARKET_FEED_DIR" ]] && MARKET_FEED_DIR="$OVERRIDE_MARKET_FEED_DIR"
[[ -n "$OVERRIDE_DSA_SIGNALS_PATH" ]] && DSA_SIGNALS_PATH="$OVERRIDE_DSA_SIGNALS_PATH"
[[ -n "$OVERRIDE_KRONOS_SIGNALS_PATH" ]] && KRONOS_SIGNALS_PATH="$OVERRIDE_KRONOS_SIGNALS_PATH"
[[ -n "$OVERRIDE_TECHNICAL_SIGNALS_PATH" ]] && TECHNICAL_SIGNALS_PATH="$OVERRIDE_TECHNICAL_SIGNALS_PATH"
[[ -n "$OVERRIDE_DAILY_PLAN_PATH" ]] && DAILY_PLAN_PATH="$OVERRIDE_DAILY_PLAN_PATH"
[[ -n "$OVERRIDE_DAILY_PLAN_MARKDOWN_PATH" ]] && DAILY_PLAN_MARKDOWN_PATH="$OVERRIDE_DAILY_PLAN_MARKDOWN_PATH"
[[ -n "$OVERRIDE_DYNAMIC_ALLOWLIST_PATH" ]] && DYNAMIC_ALLOWLIST_PATH="$OVERRIDE_DYNAMIC_ALLOWLIST_PATH"
[[ -n "$OVERRIDE_TODAY_ALLOWLIST_PATH" ]] && TODAY_ALLOWLIST_PATH="$OVERRIDE_TODAY_ALLOWLIST_PATH"
[[ -n "$OVERRIDE_DAILY_USAGE_PATH" ]] && DAILY_USAGE_PATH="$OVERRIDE_DAILY_USAGE_PATH"
[[ -n "$OVERRIDE_ACCOUNT_SNAPSHOT_PATH" ]] && ACCOUNT_SNAPSHOT_PATH="$OVERRIDE_ACCOUNT_SNAPSHOT_PATH"
[[ -n "$OVERRIDE_MARKET_CALENDAR_PATH" ]] && MARKET_CALENDAR_PATH="$OVERRIDE_MARKET_CALENDAR_PATH"
[[ -n "$OVERRIDE_QUOTE_SNAPSHOT_CORE_PATH" ]] && QUOTE_SNAPSHOT_CORE_PATH="$OVERRIDE_QUOTE_SNAPSHOT_CORE_PATH"
[[ -n "$OVERRIDE_CANDIDATE_SNAPSHOT_PATH" ]] && CANDIDATE_SNAPSHOT_PATH="$OVERRIDE_CANDIDATE_SNAPSHOT_PATH"
[[ -n "$OVERRIDE_QUOTE_SNAPSHOT_CANDIDATES_PATH" ]] && QUOTE_SNAPSHOT_CANDIDATES_PATH="$OVERRIDE_QUOTE_SNAPSHOT_CANDIDATES_PATH"
[[ -n "$OVERRIDE_TRADABILITY_SNAPSHOT_PATH" ]] && TRADABILITY_SNAPSHOT_PATH="$OVERRIDE_TRADABILITY_SNAPSHOT_PATH"
[[ -n "$OVERRIDE_CATALYST_SNAPSHOT_PATH" ]] && CATALYST_SNAPSHOT_PATH="$OVERRIDE_CATALYST_SNAPSHOT_PATH"
[[ -n "$OVERRIDE_DECISIONS_LOG_PATH" ]] && DECISIONS_LOG_PATH="$OVERRIDE_DECISIONS_LOG_PATH"
[[ -n "$OVERRIDE_ORDERS_LOG_PATH" ]] && ORDERS_LOG_PATH="$OVERRIDE_ORDERS_LOG_PATH"
[[ -n "$OVERRIDE_POSTMARKET_SUMMARY_PATH" ]] && POSTMARKET_SUMMARY_PATH="$OVERRIDE_POSTMARKET_SUMMARY_PATH"
[[ -n "$OVERRIDE_PAPER_STARTING_CASH" ]] && PAPER_STARTING_CASH="$OVERRIDE_PAPER_STARTING_CASH"
[[ -n "$OVERRIDE_KRONOS_PYTHON_BIN" ]] && KRONOS_PYTHON_BIN="$OVERRIDE_KRONOS_PYTHON_BIN"
[[ -n "$OVERRIDE_KRONOS_PROJECT_ROOT" ]] && KRONOS_PROJECT_ROOT="$OVERRIDE_KRONOS_PROJECT_ROOT"
[[ -n "$OVERRIDE_KRONOS_MODEL_NAME" ]] && KRONOS_MODEL_NAME="$OVERRIDE_KRONOS_MODEL_NAME"
[[ -n "$OVERRIDE_KRONOS_TOKENIZER_NAME" ]] && KRONOS_TOKENIZER_NAME="$OVERRIDE_KRONOS_TOKENIZER_NAME"
[[ -n "$OVERRIDE_KRONOS_TIMEFRAME" ]] && KRONOS_TIMEFRAME="$OVERRIDE_KRONOS_TIMEFRAME"
[[ -n "$OVERRIDE_KRONOS_LOOKBACK_BARS" ]] && KRONOS_LOOKBACK_BARS="$OVERRIDE_KRONOS_LOOKBACK_BARS"
[[ -n "$OVERRIDE_KRONOS_HORIZON_BARS" ]] && KRONOS_HORIZON_BARS="$OVERRIDE_KRONOS_HORIZON_BARS"
[[ -n "$OVERRIDE_KRONOS_TEMPERATURE" ]] && KRONOS_TEMPERATURE="$OVERRIDE_KRONOS_TEMPERATURE"
[[ -n "$OVERRIDE_KRONOS_TOP_P" ]] && KRONOS_TOP_P="$OVERRIDE_KRONOS_TOP_P"
[[ -n "$OVERRIDE_KRONOS_SAMPLE_COUNT" ]] && KRONOS_SAMPLE_COUNT="$OVERRIDE_KRONOS_SAMPLE_COUNT"
[[ -n "$OVERRIDE_KRONOS_MIN_CONFIDENCE" ]] && KRONOS_MIN_CONFIDENCE="$OVERRIDE_KRONOS_MIN_CONFIDENCE"

TRADING_MODE="${TRADING_MODE:-paper}"
CODEX_MODEL="${CODEX_MODEL:-gpt-5.5}"
CODEX_BIN="${CODEX_BIN:-codex}"
RISK_TIER="${RISK_TIER:-0}"
MAX_SINGLE_ORDER_NOTIONAL="${MAX_SINGLE_ORDER_NOTIONAL:-10}"
MAX_DAILY_NOTIONAL="${MAX_DAILY_NOTIONAL:-25}"
CODEX_EXEC_TIMEOUT_SEC="${CODEX_EXEC_TIMEOUT_SEC:-600}"
ENABLE_DSA_SIGNAL_LAYER="${ENABLE_DSA_SIGNAL_LAYER:-1}"
ENABLE_KRONOS_SIGNAL_LAYER="${ENABLE_KRONOS_SIGNAL_LAYER:-1}"
ENABLE_MARKET_FEED_LAYER="${ENABLE_MARKET_FEED_LAYER:-1}"
ENABLE_TECHNICAL_SIGNAL_LAYER="${ENABLE_TECHNICAL_SIGNAL_LAYER:-1}"
MARKET_FEED_PYTHON_BIN="${MARKET_FEED_PYTHON_BIN:-python3}"
MARKET_FEED_TIMEFRAMES="${MARKET_FEED_TIMEFRAMES:-1w,1d,1h,15m}"
MARKET_FEED_NEWS_LIMIT="${MARKET_FEED_NEWS_LIMIT:-5}"
KRONOS_PYTHON_BIN="${KRONOS_PYTHON_BIN:-$AGENT_ROOT/.venv-kronos/bin/python}"
KRONOS_PROJECT_ROOT="${KRONOS_PROJECT_ROOT:-$AGENT_ROOT/.vendor/kronos}"
KRONOS_MODEL_NAME="${KRONOS_MODEL_NAME:-NeoQuasar/Kronos-small}"
KRONOS_TOKENIZER_NAME="${KRONOS_TOKENIZER_NAME:-NeoQuasar/Kronos-Tokenizer-base}"
KRONOS_TIMEFRAME="${KRONOS_TIMEFRAME:-30m}"
KRONOS_LOOKBACK_BARS="${KRONOS_LOOKBACK_BARS:-400}"
KRONOS_HORIZON_BARS="${KRONOS_HORIZON_BARS:-8}"
KRONOS_TEMPERATURE="${KRONOS_TEMPERATURE:-1.0}"
KRONOS_TOP_P="${KRONOS_TOP_P:-0.9}"
KRONOS_SAMPLE_COUNT="${KRONOS_SAMPLE_COUNT:-1}"
KRONOS_MIN_CONFIDENCE="${KRONOS_MIN_CONFIDENCE:-0.60}"
export ENABLE_KRONOS_SIGNAL_LAYER
export KRONOS_PYTHON_BIN
export KRONOS_PROJECT_ROOT
export KRONOS_MODEL_NAME
export KRONOS_TOKENIZER_NAME
export KRONOS_TIMEFRAME
export KRONOS_LOOKBACK_BARS
export KRONOS_HORIZON_BARS
export KRONOS_TEMPERATURE
export KRONOS_TOP_P
export KRONOS_SAMPLE_COUNT
export KRONOS_MIN_CONFIDENCE

pt_now() {
  TZ=America/Los_Angeles date '+%Y-%m-%dT%H:%M:%S%z'
}

pt_date() {
  TZ=America/Los_Angeles date '+%Y-%m-%d'
}

RUN_DATE_PT="${RUN_DATE_PT:-$(pt_date)}"
RUN_STATE_DIR="${AGENT_ROOT}/runtime/state/runs/${RUN_DATE_PT}"
RUN_LOG_DIR="${AGENT_ROOT}/runtime/logs/runs/${RUN_DATE_PT}"
SIGNALS_DIR="${RUN_STATE_DIR}/signals"
PLANNER_DIR="${RUN_STATE_DIR}/planner"
ARCHIVE_DIR="${RUN_STATE_DIR}/archive"
MARKET_FEED_DIR="${MARKET_FEED_DIR:-${RUN_STATE_DIR}/market_feed}"
DSA_SIGNALS_PATH="${DSA_SIGNALS_PATH:-${SIGNALS_DIR}/dsa_signals.json}"
KRONOS_SIGNALS_PATH="${KRONOS_SIGNALS_PATH:-${SIGNALS_DIR}/kronos_signals.json}"
TECHNICAL_SIGNALS_PATH="${TECHNICAL_SIGNALS_PATH:-${SIGNALS_DIR}/technical_signals.json}"
TRADER_WATCH_LEVELS_PATH="${TRADER_WATCH_LEVELS_PATH:-${PLANNER_DIR}/trader_watch_levels.json}"
DAILY_PLAN_PATH="${DAILY_PLAN_PATH:-${PLANNER_DIR}/daily_plan.json}"
DAILY_PLAN_MARKDOWN_PATH="${DAILY_PLAN_MARKDOWN_PATH:-${PLANNER_DIR}/daily_plan.md}"
DYNAMIC_ALLOWLIST_PATH="${DYNAMIC_ALLOWLIST_PATH:-${PLANNER_DIR}/dynamic_allowlist.json}"
TODAY_ALLOWLIST_PATH="${TODAY_ALLOWLIST_PATH:-${PLANNER_DIR}/today_allowlist.txt}"
DAILY_USAGE_PATH="${DAILY_USAGE_PATH:-${PLANNER_DIR}/daily_usage.json}"
ACCOUNT_SNAPSHOT_PATH="${ACCOUNT_SNAPSHOT_PATH:-${PLANNER_DIR}/account_snapshot.json}"
CAPITAL_SNAPSHOT_PATH="${CAPITAL_SNAPSHOT_PATH:-${PLANNER_DIR}/capital_snapshot.json}"
MARKET_CALENDAR_PATH="${MARKET_CALENDAR_PATH:-${PLANNER_DIR}/market_calendar.json}"
QUOTE_SNAPSHOT_CORE_PATH="${QUOTE_SNAPSHOT_CORE_PATH:-${PLANNER_DIR}/quote_snapshot_core.json}"
CANDIDATE_SNAPSHOT_PATH="${CANDIDATE_SNAPSHOT_PATH:-${PLANNER_DIR}/candidate_snapshot.json}"
CANDIDATE_SCORES_PATH="${CANDIDATE_SCORES_PATH:-${PLANNER_DIR}/candidate_scores.json}"
QUOTE_SNAPSHOT_CANDIDATES_PATH="${QUOTE_SNAPSHOT_CANDIDATES_PATH:-${PLANNER_DIR}/quote_snapshot_candidates.json}"
TRADABILITY_SNAPSHOT_PATH="${TRADABILITY_SNAPSHOT_PATH:-${PLANNER_DIR}/tradability_snapshot.json}"
CATALYST_SNAPSHOT_PATH="${CATALYST_SNAPSHOT_PATH:-${PLANNER_DIR}/catalyst_snapshot.json}"
DATA_STATUS_SUMMARY_PATH="${DATA_STATUS_SUMMARY_PATH:-${PLANNER_DIR}/data_status_summary.json}"
RISK_OVERLAY_PATH="${RISK_OVERLAY_PATH:-${PLANNER_DIR}/risk_overlay.json}"
RUN_LOG="${CODEX_RUN_LOG_PATH:-${RUN_LOG_DIR}/codex_runs.log}"
ERROR_LOG="${ERROR_LOG_PATH:-${RUN_LOG_DIR}/errors.log}"
DECISIONS_LOG="${DECISIONS_LOG_PATH:-${RUN_LOG_DIR}/decisions.jsonl}"
ORDERS_LOG="${ORDERS_LOG_PATH:-${RUN_LOG_DIR}/orders.jsonl}"
POSTMARKET_SUMMARY_PATH="${POSTMARKET_SUMMARY_PATH:-${RUN_LOG_DIR}/postmarket_summary.md}"
PAPER_STARTING_CASH="${PAPER_STARTING_CASH:-400000}"

mkdir -p "$RUN_LOG_DIR" "$RUN_STATE_DIR" "$SIGNALS_DIR" "$PLANNER_DIR" "$ARCHIVE_DIR"
: >> "$RUN_LOG"
: >> "$ERROR_LOG"
: >> "$DECISIONS_LOG"
: >> "$ORDERS_LOG"

export ENABLE_MARKET_FEED_LAYER
export ENABLE_TECHNICAL_SIGNAL_LAYER
export SRC_ROOT
export RUN_DATE_PT
export RUN_STATE_DIR
export RUN_LOG_DIR
export SIGNALS_DIR
export PLANNER_DIR
export ARCHIVE_DIR
export MARKET_FEED_PYTHON_BIN
export MARKET_FEED_TIMEFRAMES
export MARKET_FEED_NEWS_LIMIT
export MARKET_FEED_DIR
export DSA_SIGNALS_PATH
export KRONOS_SIGNALS_PATH
export TECHNICAL_SIGNALS_PATH
export TRADER_WATCH_LEVELS_PATH
export DAILY_PLAN_PATH
export DAILY_PLAN_MARKDOWN_PATH
export DYNAMIC_ALLOWLIST_PATH
export TODAY_ALLOWLIST_PATH
export DAILY_USAGE_PATH
export ACCOUNT_SNAPSHOT_PATH
export CAPITAL_SNAPSHOT_PATH
export MARKET_CALENDAR_PATH
export QUOTE_SNAPSHOT_CORE_PATH
export CANDIDATE_SNAPSHOT_PATH
export CANDIDATE_SCORES_PATH
export QUOTE_SNAPSHOT_CANDIDATES_PATH
export TRADABILITY_SNAPSHOT_PATH
export CATALYST_SNAPSHOT_PATH
export DATA_STATUS_SUMMARY_PATH
export RISK_OVERLAY_PATH
export CODEX_RUN_LOG_PATH="$RUN_LOG"
export ERROR_LOG_PATH="$ERROR_LOG"
export DECISIONS_LOG_PATH="$DECISIONS_LOG"
export ORDERS_LOG_PATH="$ORDERS_LOG"
export POSTMARKET_SUMMARY_PATH
export PAPER_STARTING_CASH

log_line() {
  printf '%s %s\n' "$(pt_now)" "$*" >> "$RUN_LOG"
}

kill_switch_status() {
  if [[ -f "$AGENT_ROOT/KILL_SWITCH" ]]; then
    printf 'present'
  else
    printf 'absent'
  fi
}

is_weekday_pt() {
  local weekday
  weekday="$(TZ=America/Los_Angeles date '+%w')"
  [[ "$weekday" -ge 1 && "$weekday" -le 5 ]]
}

is_intraday_window_pt() {
  local hour minute current start end
  hour="$(TZ=America/Los_Angeles date '+%H')"
  minute="$(TZ=America/Los_Angeles date '+%M')"
  current=$((10#$hour * 60 + 10#$minute))
  start=$((6 * 60 + 45))
  end=$((12 * 60 + 55))
  [[ "$current" -ge "$start" && "$current" -le "$end" ]]
}

append_local_decision() {
  local run_kind="$1"
  local decision="$2"
  local reason="$3"
  printf '{"timestamp":"%s","run_kind":"%s","trading_mode":"%s","decision":"%s","action_taken":"none","reason":"%s"}\n' \
    "$(pt_now)" "$run_kind" "$TRADING_MODE" "$decision" "$reason" >> "$DECISIONS_LOG"
}

market_feed_python_has_deps() {
  local python_bin="$1"
  "$python_bin" -c 'import yfinance' >/dev/null 2>&1
}

resolve_market_feed_python_bin() {
  local candidate resolved

  if market_feed_python_has_deps "$MARKET_FEED_PYTHON_BIN"; then
    printf '%s\n' "$MARKET_FEED_PYTHON_BIN"
    return 0
  fi

  for candidate in \
    "$AGENT_ROOT/.venv/bin/python" \
    "${CONDA_PREFIX:-}/bin/python" \
    python3 \
    python \
    /opt/miniconda3/bin/python3 \
    /opt/homebrew/bin/python3 \
    /usr/local/bin/python3 \
    /usr/bin/python3; do
    [[ -n "$candidate" ]] || continue
    if [[ "$candidate" == */* ]]; then
      [[ -x "$candidate" ]] || continue
      resolved="$candidate"
    else
      resolved="$(command -v "$candidate" 2>/dev/null || true)"
      [[ -n "$resolved" ]] || continue
    fi
    if market_feed_python_has_deps "$resolved"; then
      printf '%s\n' "$resolved"
      return 0
    fi
  done

  printf '%s\n' "$MARKET_FEED_PYTHON_BIN"
  return 1
}

acquire_lock() {
  local name="$1"
  local lock_dir="$AGENT_ROOT/runtime/state/${name}.lock"
  if ! mkdir "$lock_dir" 2>/dev/null; then
    log_line "$name lock exists, skipping run."
    exit 0
  fi
  trap "rmdir '$lock_dir' 2>/dev/null || true" EXIT
}

build_runtime_block() {
  local run_kind="$1"
  cat <<RUNTIME
<runtime>
RUN_KIND=$run_kind
RUN_STARTED_AT=$(pt_now)
RUN_DATE_PT=$RUN_DATE_PT
TIMEZONE=America/Los_Angeles
AGENT_ROOT=$AGENT_ROOT
RUN_STATE_DIR=$RUN_STATE_DIR
RUN_LOGS_DIR=$RUN_LOG_DIR
SIGNALS_DIR=$SIGNALS_DIR
PLANNER_DIR=$PLANNER_DIR
ARCHIVE_DIR=$ARCHIVE_DIR
TRADING_MODE=$TRADING_MODE
RISK_TIER=$RISK_TIER
KILL_SWITCH_STATUS=$(kill_switch_status)
ALLOW_OUTSIDE_MARKET_TEST=${ALLOW_OUTSIDE_MARKET_TEST:-0}
MAX_SINGLE_ORDER_NOTIONAL=$MAX_SINGLE_ORDER_NOTIONAL
MAX_DAILY_NOTIONAL=$MAX_DAILY_NOTIONAL
CODEX_EXEC_DRY_RUN=${CODEX_EXEC_DRY_RUN:-0}
ENABLE_DSA_SIGNAL_LAYER=$ENABLE_DSA_SIGNAL_LAYER
ENABLE_MARKET_FEED_LAYER=$ENABLE_MARKET_FEED_LAYER
ENABLE_TECHNICAL_SIGNAL_LAYER=$ENABLE_TECHNICAL_SIGNAL_LAYER
MARKET_FEED_DIR=$MARKET_FEED_DIR
DSA_SIGNALS_PATH=$DSA_SIGNALS_PATH
KRONOS_SIGNALS_PATH=$KRONOS_SIGNALS_PATH
TECHNICAL_SIGNALS_PATH=$TECHNICAL_SIGNALS_PATH
DAILY_PLAN_PATH=$DAILY_PLAN_PATH
DAILY_PLAN_MARKDOWN_PATH=$DAILY_PLAN_MARKDOWN_PATH
DYNAMIC_ALLOWLIST_PATH=$DYNAMIC_ALLOWLIST_PATH
TODAY_ALLOWLIST_PATH=$TODAY_ALLOWLIST_PATH
DAILY_USAGE_PATH=$DAILY_USAGE_PATH
ACCOUNT_SNAPSHOT_PATH=$ACCOUNT_SNAPSHOT_PATH
MARKET_CALENDAR_PATH=$MARKET_CALENDAR_PATH
QUOTE_SNAPSHOT_CORE_PATH=$QUOTE_SNAPSHOT_CORE_PATH
CANDIDATE_SNAPSHOT_PATH=$CANDIDATE_SNAPSHOT_PATH
QUOTE_SNAPSHOT_CANDIDATES_PATH=$QUOTE_SNAPSHOT_CANDIDATES_PATH
TRADABILITY_SNAPSHOT_PATH=$TRADABILITY_SNAPSHOT_PATH
CATALYST_SNAPSHOT_PATH=$CATALYST_SNAPSHOT_PATH
DECISIONS_LOG_PATH=$DECISIONS_LOG
ORDERS_LOG_PATH=$ORDERS_LOG
POSTMARKET_SUMMARY_PATH=$POSTMARKET_SUMMARY_PATH
</runtime>

RUNTIME
}

run_codex_prompt() {
  local run_kind="$1"
  local prompt_file="$2"

  if [[ ! -f "$prompt_file" ]]; then
    log_line "$run_kind prompt file missing: $prompt_file"
    printf '%s missing prompt file: %s\n' "$(pt_now)" "$prompt_file" >> "$ERROR_LOG"
    return 1
  fi

  log_line "$run_kind starting mode=$TRADING_MODE model=$CODEX_MODEL kill_switch=$(kill_switch_status)"

  if [[ "${CODEX_EXEC_DRY_RUN:-0}" == "1" ]]; then
    log_line "$run_kind CODEX_EXEC_DRY_RUN=1, not invoking codex exec."
    printf '%s DRY_RUN %s mode=%s kill_switch=%s prompt=%s\n' \
      "$(pt_now)" "$run_kind" "$TRADING_MODE" "$(kill_switch_status)" "$prompt_file" >> "$RUN_LOG"
    return 0
  fi

  if ! command -v "$CODEX_BIN" >/dev/null 2>&1; then
    log_line "$run_kind failed: CODEX_BIN not found: $CODEX_BIN"
    printf '%s CODEX_BIN not found: %s\n' "$(pt_now)" "$CODEX_BIN" >> "$ERROR_LOG"
    return 127
  fi

  local prompt_input
  prompt_input="$(mktemp "${TMPDIR:-/tmp}/robinhood-codex-${run_kind}.XXXXXX")"
  {
    build_runtime_block "$run_kind"
    cat "$prompt_file"
  } > "$prompt_input"

  set +e
  "$CODEX_BIN" --ask-for-approval never exec \
    --cd "$AGENT_ROOT" \
    --skip-git-repo-check \
    --sandbox workspace-write \
    -m "$CODEX_MODEL" \
    - < "$prompt_input" >> "$RUN_LOG" 2>> "$ERROR_LOG" &
  local codex_pid=$!
  (
    sleep "$CODEX_EXEC_TIMEOUT_SEC"
    if kill -0 "$codex_pid" 2>/dev/null; then
      printf '%s %s codex exec timeout after %ss\n' "$(pt_now)" "$run_kind" "$CODEX_EXEC_TIMEOUT_SEC" >> "$ERROR_LOG"
      kill -TERM "$codex_pid" 2>/dev/null || true
      sleep 5
      kill -KILL "$codex_pid" 2>/dev/null || true
    fi
  ) &
  local watchdog_pid=$!

  wait "$codex_pid"
  local status=$?
  kill "$watchdog_pid" 2>/dev/null || true
  wait "$watchdog_pid" 2>/dev/null || true
  rm -f "$prompt_input"
  set -e

  if [[ "$status" -ne 0 ]]; then
    log_line "$run_kind failed status=$status"
    return "$status"
  fi

  log_line "$run_kind completed status=0"
}
